services:
  - type: web
    name: nishmitha-roots-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8081
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: nishmitha-roots-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: nishmitha-roots-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: nishmitha-roots-db
          property: password

databases:
  - name: nishmitha-roots-db
    databaseName: roots
    user: rootsuser
    plan: free